oauth10a.provider:
  temporary.credentials.url: https://api.twitter.com/oauth/request_token
  authorize.url: https://api.twitter.com/oauth/authorize
  token.credentials.url: https://api.twitter.com/oauth/access_token
  post.url: https://api.twitter.com/1.1/statuses/update.json


oauth10a.consumer:
  key: YourConsumerKey
  secret: YourConsumerSecret
  callback.url: YourCallbackURL