oauth10a.provider:
  request.token.url: https://api.twitter.com/oauth/authorize

oauth10a.consumer:
  key: 8Y3anpLDzrFEY8a3bHL7NNugL
  secret: HoGAE6K7QuV9dJ6WhWhSSziUnXv12GyF78uZEr0g4YKt1WEIV7
  callback.url: http://twitter-app.homoefficio.io/oauth/callback