oauth10a.provider:
  temporary.credentials.url: https://api.twitter.com/oauth/request_token
  authorize.url: https://api.twitter.com/oauth/authorize
  token.credentials.url: https://api.twitter.com/oauth/access_token


oauth10a.consumer:
  key: 8Y3anpLDzrFEY8a3bHL7NNugL
  secret: HoGAE6K7QuV9dJ6WhWhSSziUnXv12GyF78uZEr0g4YKt1WEIV7
  callback.url: http://twitter-app.homoefficio.io:8080/oauth/callback