package io.homo.efficio.scratchpad.oauth10a.consumer.domain;

import io.homo.efficio.scratchpad.oauth10a.consumer.util.OAuthConstants;
import io.homo.efficio.scratchpad.oauth10a.consumer.util.OAuthUtils;
import lombok.Data;
import org.springframework.http.HttpMethod;

import javax.servlet.http.HttpServletRequest;
import java.io.BufferedReader;
import java.io.IOException;

/**
 * @author homo.efficio@gmail.com
 * Created on 2018-08-18.
 */
@Data
public class OAuthRequestHeader {

    private String httpMethod;

    private String scheme;

    private String serverName;

    private int serverPort;

    private String temporaryCredentialsUrl;

    private String queryString;

    private String contentType;

    private String requestBody;

    private String oauthConsumerKey;

    private String oauthConsumerSecret;

    private String oauthCallbackUrl;

    private String oauthVerifier;

    //   A nonce is a random string, uniquely generated by the client to allow
    //   the server to verify that a request has never been made before and
    //   helps prevent replay attacks when requests are made over a non-secure
    //   channel.  The nonce value MUST be unique across all requests with the
    //   same timestamp, client credentials, and token combinations.
    //   The parameter MAY be omitted when using the "PLAINTEXT" signature method.
    private String oauthNonce;

    private String oauthSignature;

    private String oauthSignatureMethod = OAuthConstants.OAUTH_SIGNATURE_METHOD_HMAC_SHA1;

    //   The timestamp value MUST be a positive integer.  Unless otherwise
    //   specified by the server's documentation, the timestamp is expressed
    //   in the number of seconds since January 1, 1970 00:00:00 GMT.
    //   The parameter MAY be omitted when using the "PLAINTEXT" signature method.
    private String oauthTimestamp;

    private String oauthToken;

    private String oauthTokenSecret;

    private String oauthVersion = OAuthConstants.VERSION_1_0;

    public OAuthRequestHeader(HttpServletRequest request,
                              String temporaryCredentialsUrl,
                              String oauthConsumerKey,
                              String oauthConsumerSecret,
                              String oauthCallbackUrl) {
        this(request, temporaryCredentialsUrl, oauthConsumerKey, oauthConsumerSecret, oauthCallbackUrl, "", "", "");
    }

    public OAuthRequestHeader(HttpServletRequest request,
                              String temporaryCredentialsUrl,
                              String oauthConsumerKey,
                              String oauthConsumerSecret,
                              String oauthCallbackUrl,
                              String oauthToken,
                              String oauthTokenSecret,
                              String oauthVerifier) {
        this.httpMethod = HttpMethod.POST.toString();
        this.scheme = request.getScheme();
        this.serverName = request.getServerName();
        this.serverPort = request.getServerPort();
        this.queryString = request.getQueryString();
        this.contentType = request.getContentType();
        this.requestBody = getRequestBody(request);
        this.temporaryCredentialsUrl = temporaryCredentialsUrl;
        this.oauthConsumerKey = oauthConsumerKey;
        this.oauthConsumerSecret = oauthConsumerSecret;
        this.oauthCallbackUrl = oauthCallbackUrl;
        this.oauthToken = oauthToken;
        this.oauthTokenSecret = oauthTokenSecret;
        this.oauthVerifier = oauthVerifier;
        this.oauthTimestamp = String.valueOf(System.currentTimeMillis() / 1000);
        this.oauthNonce = OAuthUtils.generateNonce();
        this.oauthSignature = OAuthUtils.generateSignature(this, this.oauthConsumerSecret, this.oauthTokenSecret);
    }

    private String getRequestBody(HttpServletRequest request) {
        try {
            final BufferedReader reader = request.getReader();
            StringBuilder sb = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                sb.append(line);
            }
            return sb.toString();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public String getAuthorizationHeader() {
        final StringBuilder sb = new StringBuilder();
        sb.append("OAuth ")
                .append(OAuthConstants.OAUTH_CONSUMER_KEY).append("=\"").append(this.oauthConsumerKey).append("\", ")
                .append(OAuthConstants.OAUTH_SIGNATURE_METHOD).append("=\"").append(this.oauthSignatureMethod).append("\", ")
                .append(OAuthConstants.OAUTH_TIMESTAMP).append("=\"").append(this.oauthTimestamp).append("\", ")
                .append(OAuthConstants.OAUTH_NONCE).append("=\"").append(this.oauthNonce).append("\", ")
                .append(OAuthConstants.OAUTH_VERSION).append("=\"").append(this.oauthVersion).append("\", ")
                .append(OAuthConstants.OAUTH_CALLBACK).append("=\"").append(OAuthUtils.getUrlEncoded(this.oauthCallbackUrl)).append("\", ")
                .append(OAuthConstants.OAUTH_SIGNATURE).append("=\"").append(OAuthUtils.getUrlEncoded(this.oauthSignature)).append("\"");
        return sb.toString();
    }

    public String getTokenCredentialsHeader() {
        final StringBuilder sb = new StringBuilder();
        sb.append("OAuth ")
                .append(OAuthConstants.OAUTH_CONSUMER_KEY).append("=\"").append(this.oauthConsumerKey).append("\", ")
                .append(OAuthConstants.OAUTH_TOKEN).append("=\"").append(this.oauthToken).append("\", ")
                .append(OAuthConstants.OAUTH_VERIFIER).append("=\"").append(this.oauthVerifier).append("\", ")
                .append(OAuthConstants.OAUTH_SIGNATURE_METHOD).append("=\"").append(this.oauthSignatureMethod).append("\", ")
                .append(OAuthConstants.OAUTH_TIMESTAMP).append("=\"").append(this.oauthTimestamp).append("\", ")
                .append(OAuthConstants.OAUTH_NONCE).append("=\"").append(this.oauthNonce).append("\", ")
                .append(OAuthConstants.OAUTH_VERSION).append("=\"").append(this.oauthVersion).append("\", ")
                .append(OAuthConstants.OAUTH_CALLBACK).append("=\"").append(OAuthUtils.getUrlEncoded(this.oauthCallbackUrl)).append("\", ")
                .append(OAuthConstants.OAUTH_SIGNATURE).append("=\"").append(OAuthUtils.getUrlEncoded(this.oauthSignature)).append("\"");
        return sb.toString();
    }
}
